### ISSUE TITLE
api barfing - oh noes!

### ISSUE THREAD

**Issue by ahoward** [datocms/ruby-datocms-client#5]
```bash
clickclean-site (master)*$ ./bin/dato dump '--token=xxxxx'
Fetching content from DatoCMS... /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ruby-datocms-client-afe7a14be605/lib/dato/site/client.rb:78:in `rescue in request': DatoCMS API Error (Dato::ApiError)
Status: 422
Response:
{
  "data": [
    {
      "id": "CONTENT_TYPE_NOT_FOUND",
      "type": "api_error",
      "attributes": {
        "details": {
        }
      }
    }
  ]
}
        from /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ruby-datocms-client-afe7a14be605/lib/dato/site/client.rb:69:in `request'
        from /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ruby-datocms-client-afe7a14be605/lib/dato/local/loader.rb:35:in `all_items'
        from /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ruby-datocms-client-afe7a14be605/lib/dato/local/loader.rb:19:in `load'
        from /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ruby-datocms-client-afe7a14be605/lib/dato/dump/runner.rb:21:in `run'
        from /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ruby-datocms-client-afe7a14be605/lib/dato/dump/cli.rb:24:in `dump'
        from /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/ahoward/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ruby-datocms-client-afe7a14be605/exe/dato:7:in `<top (required)>'
        from ./bin/dato:17:in `load'
        from ./bin/dato:17:in `<main>'

```

**Comment by stefanoverna** [comment]
@ahoward should be fixed now, thanks for the report!

**Comment by ahoward** [comment]
thank you @stefanoverna !
